//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RossLean.GenericsAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RossLean.GenericsAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has specified explicit type constraints, preventing the type &apos;{1}&apos; from being used{2}.
        /// </summary>
        internal static string GA0001_Description {
            get {
                return ResourceManager.GetString("GA0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{1}&apos; cannot be used as a generic type argument for the type &apos;{0}&apos; in this position{2}.
        /// </summary>
        internal static string GA0001_MessageFormat {
            get {
                return ResourceManager.GetString("GA0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibited type argument.
        /// </summary>
        internal static string GA0001_Title {
            get {
                return ResourceManager.GetString("GA0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type parameter &apos;{0}&apos; already includes a type constraint rule for the type &apos;{1}&apos;.
        /// </summary>
        internal static string GA0002_MessageFormat {
            get {
                return ResourceManager.GetString("GA0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply multiple constraint rules for the same type.
        /// </summary>
        internal static string GA0002_Title {
            get {
                return ResourceManager.GetString("GA0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type parameter &apos;{0}&apos; already includes the same type constraint rule for the unbound version of the generic type &apos;{1}&apos;.
        /// </summary>
        internal static string GA0003_MessageFormat {
            get {
                return ResourceManager.GetString("GA0003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant type constraint rule for both a bound and the unbound version of the same type.
        /// </summary>
        internal static string GA0003_Title {
            get {
                return ResourceManager.GetString("GA0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is an invalid type argument.
        /// </summary>
        internal static string GA0004_MessageFormat {
            get {
                return ResourceManager.GetString("GA0004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign an invalid type argument as a type constraint.
        /// </summary>
        internal static string GA0004_Title {
            get {
                return ResourceManager.GetString("GA0004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is prohibited from being used as a type argument for the type parameter &apos;{1}&apos;.
        /// </summary>
        internal static string GA0005_MessageFormat {
            get {
                return ResourceManager.GetString("GA0005_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type prohibited from generic type constraints in the constraint clause.
        /// </summary>
        internal static string GA0005_Title {
            get {
                return ResourceManager.GetString("GA0005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer declaring the constraint of a single base bound interface type in the constraints clause.
        /// </summary>
        internal static string GA0006_MessageFormat {
            get {
                return ResourceManager.GetString("GA0006_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint only permits usage of one base bound interface type.
        /// </summary>
        internal static string GA0006_Title {
            get {
                return ResourceManager.GetString("GA0006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant base type rule; the given base type &apos;{0}&apos; is sealed.
        /// </summary>
        internal static string GA0008_MessageFormat {
            get {
                return ResourceManager.GetString("GA0008_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant base type rule.
        /// </summary>
        internal static string GA0008_Title {
            get {
                return ResourceManager.GetString("GA0008_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; was declared more than once in the same constraint rule.
        /// </summary>
        internal static string GA0009_MessageFormat {
            get {
                return ResourceManager.GetString("GA0009_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate type rule.
        /// </summary>
        internal static string GA0009_Title {
            get {
                return ResourceManager.GetString("GA0009_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant explicit type prohibition; the type &apos;{0}&apos; is already prohibited based on the system&apos;s rules.
        /// </summary>
        internal static string GA0010_MessageFormat {
            get {
                return ResourceManager.GetString("GA0010_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant explicit type prohibition.
        /// </summary>
        internal static string GA0010_Title {
            get {
                return ResourceManager.GetString("GA0010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant explicit type permission; the type &apos;{0}&apos; is already permitted based on the system&apos;s rules.
        /// </summary>
        internal static string GA0011_MessageFormat {
            get {
                return ResourceManager.GetString("GA0011_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant explicit type permission.
        /// </summary>
        internal static string GA0011_Title {
            get {
                return ResourceManager.GetString("GA0011_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage of the attribute requires that at least one type is permitted.
        /// </summary>
        internal static string GA0012_MessageFormat {
            get {
                return ResourceManager.GetString("GA0012_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid usage of OnlyPermitSpecifiedTypesAttribute.
        /// </summary>
        internal static string GA0012_Title {
            get {
                return ResourceManager.GetString("GA0012_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type parameter &apos;{0}&apos; only has one explicitly specified permitted type argument (did you forget to mark the permitted type as base?).
        /// </summary>
        internal static string GA0013_MessageFormat {
            get {
                return ResourceManager.GetString("GA0013_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one type is explicitly permitted.
        /// </summary>
        internal static string GA0013_Title {
            get {
                return ResourceManager.GetString("GA0013_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant usage of the attribute; the element &apos;{0}&apos; cannot inherit other types.
        /// </summary>
        internal static string GA0014_MessageFormat {
            get {
                return ResourceManager.GetString("GA0014_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant usage of InheritBaseTypeUsageConstraintsAttribute.
        /// </summary>
        internal static string GA0014_Title {
            get {
                return ResourceManager.GetString("GA0014_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant usage of the attribute; the type &apos;{0}&apos; does not inherit other generic types.
        /// </summary>
        internal static string GA0015_MessageFormat {
            get {
                return ResourceManager.GetString("GA0015_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant usage of InheritBaseTypeUsageConstraintsAttribute.
        /// </summary>
        internal static string GA0015_Title {
            get {
                return ResourceManager.GetString("GA0015_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant usage of the attribute; the type parameter &apos;{0}&apos; is not used in any of the base types.
        /// </summary>
        internal static string GA0016_MessageFormat {
            get {
                return ResourceManager.GetString("GA0016_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant usage of InheritBaseTypeUsageConstraintsAttribute.
        /// </summary>
        internal static string GA0016_Title {
            get {
                return ResourceManager.GetString("GA0016_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The explicit type constraints for generic type parameter &apos;{0}&apos; do not match those of type parameter &apos;{1}&apos;.
        /// </summary>
        internal static string GA0017_Description {
            get {
                return ResourceManager.GetString("GA0017_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type parameter &apos;{1}&apos; cannot be used as a generic type argument for the type &apos;{0}&apos; in this position.
        /// </summary>
        internal static string GA0017_MessageFormat {
            get {
                return ResourceManager.GetString("GA0017_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type argument explicit type constraint mismatch.
        /// </summary>
        internal static string GA0017_Title {
            get {
                return ResourceManager.GetString("GA0017_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given type parameter name &apos;{0}&apos; does not reflect any locally declared type parameter.
        /// </summary>
        internal static string GA0019_MessageFormat {
            get {
                return ResourceManager.GetString("GA0019_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type parameter name.
        /// </summary>
        internal static string GA0019_Title {
            get {
                return ResourceManager.GetString("GA0019_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type constraint inheritance causes a recursion with the following path:\n{0}.
        /// </summary>
        internal static string GA0020_MessageFormat {
            get {
                return ResourceManager.GetString("GA0020_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive inheritance was detected.
        /// </summary>
        internal static string GA0020_Title {
            get {
                return ResourceManager.GetString("GA0020_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type parameter may not inherit type constraints from itself.
        /// </summary>
        internal static string GA0021_MessageFormat {
            get {
                return ResourceManager.GetString("GA0021_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot inherit from the same type parameter.
        /// </summary>
        internal static string GA0021_Title {
            get {
                return ResourceManager.GetString("GA0021_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type constraint inheritance results in a rule collision.
        /// </summary>
        internal static string GA0022_MessageFormat {
            get {
                return ResourceManager.GetString("GA0022_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting inherited type constraint rules.
        /// </summary>
        internal static string GA0022_Title {
            get {
                return ResourceManager.GetString("GA0022_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only non-generic interfaces can be type constraint profiles or type constraint profile groups.
        /// </summary>
        internal static string GA0023_MessageFormat {
            get {
                return ResourceManager.GetString("GA0023_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type constraint profile type declaration.
        /// </summary>
        internal static string GA0023_Title {
            get {
                return ResourceManager.GetString("GA0023_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type constraint profile group interfaces should not contain any non-static members.
        /// </summary>
        internal static string GA0024_MessageFormat {
            get {
                return ResourceManager.GetString("GA0024_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type constaint profile group type also implements other behavior.
        /// </summary>
        internal static string GA0024_Title {
            get {
                return ResourceManager.GetString("GA0024_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type constraint profile interfaces should not be inherited by types unrelated to type constraint profiles, or vice versa (did you forget to use the TypeConstraintProfileAttribute?).
        /// </summary>
        internal static string GA0025_MessageFormat {
            get {
                return ResourceManager.GetString("GA0025_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed type constraint profile interfaces with irrelevant ones in inheritance.
        /// </summary>
        internal static string GA0025_Title {
            get {
                return ResourceManager.GetString("GA0025_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given type does not represent a type constraint profile definition.
        /// </summary>
        internal static string GA0026_MessageFormat {
            get {
                return ResourceManager.GetString("GA0026_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type constraint profile type.
        /// </summary>
        internal static string GA0026_Title {
            get {
                return ResourceManager.GetString("GA0026_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given type does not represent a type constraint profile group definition.
        /// </summary>
        internal static string GA0027_MessageFormat {
            get {
                return ResourceManager.GetString("GA0027_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type constraint profile group type.
        /// </summary>
        internal static string GA0027_Title {
            get {
                return ResourceManager.GetString("GA0027_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another type constraint profile of the same distinct group was used for inheritance.
        /// </summary>
        internal static string GA0028_MessageFormat {
            get {
                return ResourceManager.GetString("GA0028_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting profiles of the same distinct profile group.
        /// </summary>
        internal static string GA0028_Title {
            get {
                return ResourceManager.GetString("GA0028_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interface can only be declared as a type constraint profile or a type constraint profile group.
        /// </summary>
        internal static string GA0029_MessageFormat {
            get {
                return ResourceManager.GetString("GA0029_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mutually exclusive declarations of the interface.
        /// </summary>
        internal static string GA0029_Title {
            get {
                return ResourceManager.GetString("GA0029_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type constraint-related attributes are assigned at the given interface, which is not declared as a type constraint profile (did you forget to use the TypeConstraintProfileAttribute?).
        /// </summary>
        internal static string GA0030_MessageFormat {
            get {
                return ResourceManager.GetString("GA0030_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type constraint attributes used on non-profile interface.
        /// </summary>
        internal static string GA0030_Title {
            get {
                return ResourceManager.GetString("GA0030_Title", resourceCulture);
            }
        }
    }
}
