//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RossLean.NameOn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RossLean.NameOn.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; is declared such that it only accepts full nameof expressions for the symbol kind &apos;{1}&apos;.
        /// </summary>
        internal static string NAME0001_Description {
            get {
                return ResourceManager.GetString("NAME0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value passed to &apos;{0}&apos; must be a nameof expression.
        /// </summary>
        internal static string NAME0001_Title {
            get {
                return ResourceManager.GetString("NAME0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; is declared such that it only accepts string expressions containing at least one nameof expression for the symbol kind &apos;{1}&apos;.
        /// </summary>
        internal static string NAME0002_Description {
            get {
                return ResourceManager.GetString("NAME0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value passed to &apos;{0}&apos; must contain at least one nameof expression.
        /// </summary>
        internal static string NAME0002_Title {
            get {
                return ResourceManager.GetString("NAME0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; is declared such that it does not accept full nameof expressions (expressions containing nameof expressions are still allowed) for the symbol kind &apos;{1}&apos;.
        /// </summary>
        internal static string NAME0003_Description {
            get {
                return ResourceManager.GetString("NAME0003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value passed to &apos;{0}&apos; must not be a full nameof expression.
        /// </summary>
        internal static string NAME0003_Title {
            get {
                return ResourceManager.GetString("NAME0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; is declared such that it only accepts string expressions containing no nameof expressions (full nameof expressions are also prohibited) for the symbol kind &apos;{1}&apos;.
        /// </summary>
        internal static string NAME0004_Description {
            get {
                return ResourceManager.GetString("NAME0004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value passed to &apos;{0}&apos; must contain no nameof expressions.
        /// </summary>
        internal static string NAME0004_Title {
            get {
                return ResourceManager.GetString("NAME0004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the symbol &apos;{0}&apos; does not accept string literals as assignable values.
        /// </summary>
        internal static string NAME0010_Description {
            get {
                return ResourceManager.GetString("NAME0010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This symbol cannot get nameof expressions assigned to.
        /// </summary>
        internal static string NAME0010_Title {
            get {
                return ResourceManager.GetString("NAME0010_Title", resourceCulture);
            }
        }
    }
}
