namespace RossLean.GenericsAnalyzer.CodeFixes.Test.PermittedTypeArguments;

public abstract class ConstraintClauseTypeConstraintPlacerCodeFixTests : PermittedTypeArgumentAnalyzerCodeFixTests<ConstraintClauseTypeConstraintPlacer>
{
}
