namespace RossLean.GenericsAnalyzer.CodeFixes.Test.PermittedTypeArguments;

public abstract class DuplicateAttributeArgumentRemoverCodeFixTests : PermittedTypeArgumentAnalyzerCodeFixTests<DuplicateAttributeArgumentRemover>
{
}
