namespace RossLean.GenericsAnalyzer.CodeFixes.Test.PermittedTypeArguments;

public abstract class InstanceTypeMemberRemoverCodeFixTests : PermittedTypeArgumentAnalyzerCodeFixTests<InstanceTypeMemberRemover>
{
}
