namespace RossLean.GenericsAnalyzer.CodeFixes.Test.PermittedTypeArguments;

public abstract class ProfileInterfaceDeclarerCodeFixTests : PermittedTypeArgumentAnalyzerCodeFixTests<ProfileInterfaceDeclarer>
{
}
