namespace RossLean.GenericsAnalyzer.CodeFixes.Test.PermittedTypeArguments;

public abstract class RedundantBaseTypeRuleConverterCodeFixTests : PermittedTypeArgumentAnalyzerCodeFixTests<RedundantBaseTypeRuleConverter>
{
}
