namespace RossLean.GenericsAnalyzer.CodeFixes.Test.PermittedTypeArguments;

public abstract class RedundantAttributeRemoverCodeFixTests : PermittedTypeArgumentAnalyzerCodeFixTests<RedundantAttributeRemover>
{
}
