namespace RossLean.GenericsAnalyzer.CodeFixes.Test.PermittedTypeArguments;

public abstract class RedundantAttributeArgumentRemoverCodeFixTests : PermittedTypeArgumentAnalyzerCodeFixTests<RedundantAttributeArgumentRemover>
{
}
