//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RossLean.Smarttributes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RossLean.Smarttributes.DiagnosticResources", typeof(DiagnosticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; requires that the following attributes are also present in the symbol &apos;{1}&apos;:{2}.
        /// </summary>
        internal static string SMTTR0001_MessageFormat {
            get {
                return ResourceManager.GetString("SMTTR0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute&apos;s presence requires that other attributes are also present.
        /// </summary>
        internal static string SMTTR0001_Title {
            get {
                return ResourceManager.GetString("SMTTR0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; requires that the attribute &apos;{1}&apos; can be placed on the following targets: {2}.
        /// </summary>
        internal static string SMTTR0002_MessageFormat {
            get {
                return ResourceManager.GetString("SMTTR0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute&apos;s presence requires that it can be placed on specific attribute types.
        /// </summary>
        internal static string SMTTR0002_Title {
            get {
                return ResourceManager.GetString("SMTTR0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; can only be applied to functions of kind: &apos;{1}&apos;.
        /// </summary>
        internal static string SMTTR0005_MessageFormat {
            get {
                return ResourceManager.GetString("SMTTR0005_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute can only be placed on functions of certain kinds.
        /// </summary>
        internal static string SMTTR0005_Title {
            get {
                return ResourceManager.GetString("SMTTR0005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This array argument must contain an equal number of objects matching the number of parameters in the method.
        /// </summary>
        internal static string SMTTR0010_MessageFormat {
            get {
                return ResourceManager.GetString("SMTTR0010_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided argument count mismatch.
        /// </summary>
        internal static string SMTTR0010_Title {
            get {
                return ResourceManager.GetString("SMTTR0010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This array argument must contain objects matching the types of the parameters in the method in the order they appear.
        /// </summary>
        internal static string SMTTR0011_MessageFormat {
            get {
                return ResourceManager.GetString("SMTTR0011_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided argument type mismatch.
        /// </summary>
        internal static string SMTTR0011_Title {
            get {
                return ResourceManager.GetString("SMTTR0011_Title", resourceCulture);
            }
        }
    }
}
