//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RossLean.GenericsAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RossLean.GenericsAnalyzer.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all members from type.
        /// </summary>
        internal static string AllTypeMemberRemover_Title {
            get {
                return ResourceManager.GetString("AllTypeMemberRemover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move type constrraint to constraint clause.
        /// </summary>
        internal static string ConstraintClauseTypeConstraintPlacer_Title {
            get {
                return ResourceManager.GetString("ConstraintClauseTypeConstraintPlacer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicate attribute arguments.
        /// </summary>
        internal static string DuplicateAttributeArgumentRemover_Title {
            get {
                return ResourceManager.GetString("DuplicateAttributeArgumentRemover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all instance members from type.
        /// </summary>
        internal static string InstanceTypeMemberRemover_Title {
            get {
                return ResourceManager.GetString("InstanceTypeMemberRemover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make interface a type constraint profile.
        /// </summary>
        internal static string ProfileInterfaceDeclarer_Title {
            get {
                return ResourceManager.GetString("ProfileInterfaceDeclarer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove redundant attribute argument.
        /// </summary>
        internal static string RedundantAttributeArgumentRemover_Title {
            get {
                return ResourceManager.GetString("RedundantAttributeArgumentRemover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove redundant attribute.
        /// </summary>
        internal static string RedundantAttributeRemover_Title {
            get {
                return ResourceManager.GetString("RedundantAttributeRemover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert base type rule to exact type rule.
        /// </summary>
        internal static string RedundantBaseTypeRuleConverter_Title {
            get {
                return ResourceManager.GetString("RedundantBaseTypeRuleConverter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all static members from type.
        /// </summary>
        internal static string StaticTypeMemberRemover_Title {
            get {
                return ResourceManager.GetString("StaticTypeMemberRemover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make type non-generic.
        /// </summary>
        internal static string Ungenericizer_Title {
            get {
                return ResourceManager.GetString("Ungenericizer_Title", resourceCulture);
            }
        }
    }
}
