name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Run Analyzer Tests
      run: dotnet test RossLean.NameOn/NameOn.Test/NameOn.Test.csproj
